visualizer_path: "visualizer.py"  # Путь к программе для визуализации графов
package_path: "node_modules"      # Путь к папке анализируемого пакета
output_path: "diogram.mmd"        # Путь к выходному файлу с диаграммой
