visualizer_path: "task_2.py"          # Путь к программе для визуализации графов
package_path: "express-4.21.1.zip"    # Путь к папке анализируемого пакета
output_path: "diogram.mmd"            # Путь к выходному файлу с кодом диаграммы
